# Generated by Django 4.0.5 on 2022-06-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridlayout',
            name='deviceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.devicetype'),
        ),
        migrations.AddField(
            model_name='gridlayout',
            name='show',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
