# Generated by Django 4.0.5 on 2022-06-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_gridlayout_unique_provider_patient_combination_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gridlayout',
            name='unique_provider_patient_combination',
        ),
        migrations.RemoveField(
            model_name='gridlayout',
            name='deviceType',
        ),
        migrations.AddConstraint(
            model_name='gridlayout',
            constraint=models.UniqueConstraint(fields=('provider', 'patient', 'i'), name='unique_provider_patient_combination'),
        ),
    ]
